export default {
  mapa: 'fas fa-map-marker-alt fa-lg',
  ajuste: 'fas fa-wrench',
  cliente: 'fas fa-users',
  venta: 'fas fa-file-invoice-dollar',
  remito: 'fas fa-file-export',
  usuario: 'fas fa-users',
  proveedor: 'fas fa-user-tie',
  articulo: 'fas fa-box-open',
  pedido: 'fas fa-truck',
  distrito: 'fas fa-map-marked',
  departamento: 'fas fa-map-marked-alt',
  banco: 'fas fa-university',
  marca: 'fas fa-tags',
  unidadMedida: 'fas fa-ruler',
  rubro: 'fas fa-archive',
  subRubro: 'fas fa-folder-open',
  empresa: 'fas fa-building',
  reporte_venta: 'fas fa-chart-bar',
  reporte_pedido: 'fas fa-chart-line',
  reporte_remito: 'fas fa-luggage-cart',
  reporte_recaudacion: 'fas fa-cash-register'
};
